### PR TITLE
Optimization and test infrastructure

### PR DESCRIPTION
**Pull request by doug-friedman**
I know this is a big pull request, but everything has been documented carefully below. Feel free to edit as makes sense.

- Add formal unit testing with testthat
- Move documentation over to roxygen
- Transition dependencies to imports
- Transition data to data-raw and use rda data
- Speed up the L-moments calculations (where possible)
- Make general performance improvements
- Remove pglo.R and update documentation
- Change default plot title to include "SPI"/"SPEI"" when appropriate
- Change default y-axis title to say "z-values"
- Allow user to change the title when plotting spi/spei
- Increase test coverage to 75%
- Increase test coverage to 90%

### CODE REVIEW

**Comment by sbegueria** [comment]
Hi Doug, many thanks for your extensive PR. I have just updated a new version of the library that includes some of your mods (those related to the plotting function). I will now work on merging your fork.

**Comment by doug-friedman** [comment]
Great. Thanks! 

If you've got any questions or concerns, don't hesitate to ask.

**Comment by sbegueria** [comment]
Hi Doug, I finally could find some time to work on your pull request. Since there were too many conflicts with my latest master version I did the merge by hand. Your changes are in the main branch now.

But now I have problems with the tests, since I get errors when running `test_dir('./tests')`. Of course, I get the same errors when `devtools::check()`. Did you check that?

**Comment by doug-friedman** [comment]
I'm not quite sure why it failed, but likely my inclusion of `capture.output` was the culprit. If it's creating an issue, feel free to just comment it out.

**Comment by sbegueria** [comment]
I close this now as all the suggested commits (or most part of them) have been included or have been superseded in the development version of the package.

**Pull request closed without merging**
